[project]
name = "github-mcp-server"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.115.13",
    "fastmcp>=2.8.1",
    "requests>=2.32.4",
]

[project.scripts]
github-mcp-server = "app.server:main"
